### ISSUE TITLE
Sync Page Order timeout

### ISSUE THREAD

**Issue by tillkruss** [kylephillips/wp-nested-pages#183] opened 2017-04-25 17:32 UTC
We get a timeout after 60s when ordering pages using drag&drop or manual syncing. We got about 220 pages and that should be sortable within sub 2 seconds.

How are the speed improvements coming along that are mentioned in https://github.com/kylephillips/wp-nested-pages/issues/164?

This is the request form data:

```
action: npsort
nonce: 9b921ada4a
list[0][id]: 5
list[1][id]: 1059
list[2][id]: 1604
list[3][id]: 1334
list[4][id]: 620
list[4][children][0][id]: 1613
list[4][children][0][children][0][id]: 1812
list[4][children][1][id]: 622
list[4][children][1][children][0][id]: 623
list[4][children][1][children][1][id]: 632
list[4][children][1][children][2][id]: 624
list[4][children][1][children][3][id]: 625
list[4][children][1][children][4][id]: 626
list[4][children][1][children][5][id]: 637
list[4][children][1][children][6][id]: 645
list[4][children][1][children][7][id]: 2001
list[4][children][2][id]: 678
list[4][children][2][children][0][id]: 690
list[4][children][2][children][1][id]: 679
list[4][children][2][children][2][id]: 680
list[4][children][2][children][3][id]: 681
list[4][children][2][children][4][id]: 682
list[4][children][2][children][5][id]: 683
list[5][id]: 7
list[6][id]: 9
list[6][children][0][id]: 74
list[6][children][1][id]: 76
list[6][children][2][id]: 78
list[6][children][3][id]: 81
list[7][id]: 969
list[8][id]: 1001
list[9][id]: 11
list[9][children][0][id]: 14
list[9][children][0][children][0][id]: 136
list[9][children][0][children][1][id]: 151
list[9][children][0][children][1][children][0][id]: 153
list[9][children][0][children][1][children][1][id]: 154
list[9][children][0][children][1][children][2][id]: 223
list[9][children][0][children][1][children][3][id]: 218
list[9][children][0][children][2][id]: 174
list[9][children][0][children][2][children][0][id]: 184
list[9][children][0][children][2][children][1][id]: 211
list[9][children][0][children][2][children][2][id]: 217
list[9][children][0][children][2][children][3][id]: 219
list[9][children][0][children][3][id]: 178
list[9][children][0][children][3][children][0][id]: 188
list[9][children][0][children][3][children][1][id]: 222
list[9][children][0][children][3][children][2][id]: 216
list[9][children][0][children][3][children][3][id]: 221
list[9][children][0][children][4][id]: 177
list[9][children][0][children][4][children][0][id]: 186
list[9][children][0][children][4][children][1][id]: 210
list[9][children][0][children][4][children][2][id]: 215
list[9][children][0][children][4][children][3][id]: 220
list[9][children][0][children][5][id]: 176
list[9][children][0][children][5][children][0][id]: 187
list[9][children][0][children][5][children][1][id]: 212
list[9][children][0][children][5][children][2][id]: 243
list[9][children][0][children][5][children][3][id]: 244
list[9][children][0][children][6][id]: 175
list[9][children][0][children][6][children][0][id]: 185
list[9][children][0][children][6][children][1][id]: 213
list[9][children][0][children][6][children][2][id]: 214
list[9][children][0][children][6][children][3][id]: 224
list[9][children][0][children][7][id]: 202
list[9][children][0][children][8][id]: 197
list[9][children][0][children][8][children][0][id]: 200
list[9][children][0][children][8][children][1][id]: 201
list[9][children][0][children][8][children][2][id]: 199
list[9][children][1][id]: 1006
list[9][children][2][id]: 16
list[9][children][2][children][0][id]: 266
list[9][children][2][children][1][id]: 364
list[9][children][2][children][1][children][0][id]: 366
list[9][children][2][children][1][children][1][id]: 368
list[9][children][2][children][1][children][2][id]: 370
list[9][children][2][children][1][children][3][id]: 372
list[9][children][2][children][1][children][4][id]: 374
list[9][children][2][children][1][children][5][id]: 376
list[9][children][2][children][2][id]: 391
list[9][children][2][children][2][children][0][id]: 399
list[9][children][2][children][2][children][1][id]: 393
list[9][children][2][children][2][children][2][id]: 395
list[9][children][2][children][2][children][3][id]: 397
list[9][children][2][children][3][id]: 412
list[9][children][2][children][3][children][0][id]: 414
list[9][children][2][children][3][children][1][id]: 416
list[9][children][2][children][4][id]: 421
list[9][children][2][children][4][children][0][id]: 423
list[9][children][2][children][4][children][1][id]: 425
list[9][children][2][children][5][id]: 431
list[9][children][2][children][5][children][0][id]: 441
list[9][children][2][children][5][children][1][id]: 461
list[9][children][2][children][6][id]: 433
list[9][children][2][children][6][children][0][id]: 443
list[9][children][2][children][6][children][1][id]: 463
list[9][children][2][children][6][children][2][id]: 1236
list[9][children][2][children][7][id]: 435
list[9][children][2][children][7][children][0][id]: 445
list[9][children][2][children][7][children][1][id]: 465
list[9][children][2][children][8][id]: 437
list[9][children][2][children][8][children][0][id]: 447
list[9][children][2][children][8][children][1][id]: 467
list[9][children][2][children][9][id]: 439
list[9][children][2][children][9][children][0][id]: 449
list[9][children][2][children][9][children][1][id]: 469
list[9][children][2][children][10][id]: 1047
list[9][children][2][children][11][id]: 2007
list[9][children][3][id]: 18
list[9][children][3][children][0][id]: 265
list[9][children][3][children][1][id]: 497
list[9][children][3][children][1][children][0][id]: 1602
list[9][children][3][children][1][children][1][id]: 511
list[9][children][3][children][2][id]: 499
list[9][children][3][children][2][children][0][id]: 513
list[9][children][3][children][2][children][1][id]: 516
list[9][children][3][children][2][children][2][id]: 518
list[9][children][3][children][3][id]: 500
list[9][children][3][children][3][children][0][id]: 522
list[9][children][3][children][3][children][1][id]: 524
list[9][children][3][children][4][id]: 501
list[9][children][3][children][4][children][0][id]: 526
list[9][children][3][children][4][children][1][id]: 528
list[9][children][3][children][5][id]: 503
list[9][children][3][children][5][children][0][id]: 534
list[9][children][3][children][6][id]: 502
list[9][children][3][children][6][children][0][id]: 530
list[9][children][3][children][6][children][1][id]: 532
list[9][children][3][children][7][id]: 504
list[9][children][4][id]: 53
list[9][children][4][children][0][id]: 268
list[9][children][4][children][1][id]: 536
list[9][children][4][children][1][children][0][id]: 928
list[9][children][4][children][1][children][1][id]: 538
list[9][children][4][children][1][children][2][id]: 540
list[9][children][4][children][1][children][3][id]: 542
list[9][children][4][children][1][children][4][id]: 544
list[9][children][4][children][2][id]: 546
list[9][children][4][children][2][children][0][id]: 548
list[9][children][4][children][2][children][1][id]: 550
list[9][children][4][children][2][children][2][id]: 552
list[9][children][4][children][2][children][3][id]: 554
list[9][children][4][children][2][children][4][id]: 556
list[9][children][4][children][3][id]: 558
list[9][children][4][children][3][children][0][id]: 560
list[9][children][4][children][3][children][1][id]: 562
list[9][children][4][children][3][children][2][id]: 564
list[9][children][4][children][3][children][3][id]: 566
list[9][children][4][children][3][children][4][id]: 568
list[9][children][4][children][4][id]: 570
list[9][children][4][children][4][children][0][id]: 572
list[9][children][4][children][4][children][1][id]: 574
list[9][children][4][children][4][children][2][id]: 576
list[9][children][4][children][4][children][3][id]: 578
list[9][children][4][children][4][children][4][id]: 580
list[9][children][4][children][5][id]: 582
list[9][children][4][children][5][children][0][id]: 584
list[9][children][4][children][5][children][1][id]: 586
list[9][children][4][children][5][children][2][id]: 588
list[9][children][4][children][5][children][3][id]: 590
list[9][children][4][children][5][children][4][id]: 592
list[9][children][4][children][6][id]: 594
list[9][children][4][children][6][children][0][id]: 596
list[9][children][4][children][6][children][1][id]: 598
list[9][children][4][children][6][children][2][id]: 600
list[9][children][4][children][6][children][3][id]: 602
list[9][children][4][children][6][children][4][id]: 604
list[9][children][4][children][7][id]: 607
list[9][children][4][children][7][children][0][id]: 609
list[9][children][4][children][7][children][1][id]: 611
list[9][children][4][children][7][children][2][id]: 1336
list[9][children][4][children][7][children][3][id]: 615
list[9][children][4][children][7][children][4][id]: 617
list[9][children][4][children][8][id]: 1055
list[9][children][5][id]: 54
list[9][children][5][children][0][id]: 267
list[9][children][5][children][1][id]: 1273
list[9][children][5][children][2][id]: 1275
list[9][children][5][children][3][id]: 2122
list[9][children][5][children][3][children][0][id]: 2120
list[9][children][5][children][4][id]: 1277
list[9][children][5][children][4][children][0][id]: 1279
list[9][children][5][children][4][children][0][children][0][id]: 1406
list[9][children][5][children][4][children][1][id]: 1281
list[9][children][5][children][4][children][1][children][0][id]: 1410
list[9][children][5][children][4][children][2][id]: 1283
list[9][children][5][children][4][children][2][children][0][id]: 1548
list[9][children][5][children][4][children][3][id]: 1285
list[9][children][5][children][4][children][3][children][0][id]: 1572
list[9][children][5][children][4][children][4][id]: 1287
list[9][children][5][children][4][children][4][children][0][id]: 1630
list[9][children][5][children][4][children][5][id]: 1289
list[9][children][5][children][4][children][5][children][0][id]: 1708
list[9][children][5][children][4][children][6][id]: 1291
list[9][children][5][children][4][children][6][children][0][id]: 1777
list[9][children][5][children][4][children][7][id]: 1293
list[9][children][5][children][4][children][7][children][0][id]: 1822
list[9][children][5][children][4][children][8][id]: 1295
list[9][children][5][children][4][children][8][children][0][id]: 1878
list[9][children][5][children][4][children][9][id]: 1297
list[9][children][5][children][4][children][9][children][0][id]: 1908
list[9][children][5][children][4][children][10][id]: 1299
list[9][children][5][children][4][children][10][children][0][id]: 1964
list[9][children][5][children][4][children][11][id]: 1301
list[9][children][5][children][4][children][11][children][0][id]: 2012
list[9][children][5][children][5][id]: 1303
list[9][children][5][children][5][children][0][id]: 2090
list[9][children][5][children][5][children][1][id]: 2063
list[9][children][5][children][5][children][1][children][0][id]: 2080
list[9][children][5][children][6][id]: 1305
list[9][children][5][children][7][id]: 1307
list[9][children][5][children][8][id]: 1309
list[9][children][5][children][9][id]: 1311
list[9][children][5][children][10][id]: 1313
list[9][children][5][children][11][id]: 1315
list[9][children][5][children][12][id]: 1317
list[9][children][5][children][13][id]: 1804
list[10][id]: 38
list[11][id]: 48
list[12][id]: 92
list[12][children][0][id]: 94
list[12][children][1][id]: 97
list[12][children][2][id]: 99
post_type: page
syncmenu: nosync
```

**Comment by kylephillips** [comment] 2017-05-16 15:22
Duplicate of #127

**Closed by kylephillips** 2017-05-16 15:22 UTC
