### ISSUE TITLE
Error message, illegal string offset

### ISSUE THREAD

**Issue by gccwillis** [kylephillips/wp-nested-pages#326] opened 2022-03-16 01:24 UTC
I get several error messages like this when I go to the Nested Pages screen in WP. Any suggestions of a fix? Thanks.

Warning: Illegal string offset 'page' in /users/ipowerma/public_html/wp-content/plugins/wp-nested-pages/app/Entities/Listing/ListingRepository.php on line 33

Notice: Array to string conversion in /users/ipowerma/public_html/wp-content/plugins/wp-nested-pages/app/Entities/Listing/ListingRepository.php on line 33

**Comment by EliasKotlyar** [comment] 2022-03-16 17:56
I can confirm that i have this errors. My Errors are like that:

Warning: Illegal string offset 'page' in /wp-content/plugins/wp-nested-pages/app/Entities/Listing/ListingRepository.php on line 33

Warning: Illegal string offset 'page' in /wp-content/plugins/wp-nested-pages/app/Entities/Listing/ListingRepository.php on line 34

Warning: array_intersect(): Expected parameter 1 to be an array, string given in /wp-content/plugins/wp-nested-pages/app/Entities/Listing/Listing.php on line 317

**Comment by kristianHH** [comment] 2022-04-08 18:46
**I also have this exact error. What could be the reason?**


Warning: Illegal string offset 'page' in /wp-content/plugins/wp-nested-pages/app/Entities/Listing/ListingRepository.php on line 33

Warning: Illegal string offset 'page' in /wp-content/plugins/wp-nested-pages/app/Entities/Listing/ListingRepository.php on line 34

Warning: array_intersect(): Expected parameter 1 to be an array, string given in /wp-content/plugins/wp-nested-pages/app/Entities/Listing/Listing.php on line 317

**Comment by kylephillips** [comment] 2022-08-19 19:00
Fixed in 310b72015e5473fbb44f15271650d72d46545fd0

**Closed by kylephillips** 2022-08-19 19:00 UTC
